# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
- rm -rf ~/Library/Developer/Xcode/DerivedData
script:
- set -o pipefail && xcodebuild test -workspace Example/Ohana.xcworkspace -scheme TravisCIScheme -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
